export const firstName = [
    'Bubbles',
    'Snickersnee',
    'Quackery',
    'Skippy',
    'Fizzles',
    'Ziggy',
    'Noodle',
    'Tootsie',
    'Puddles',
    'Jibber',
    'Wally',
    'Chuckles',
    'Doodlebug',
    'Giggles',
    'Scooby',
    'Flapjack',
    'Snookums',
    'Tinker',
    'Bumpkin',
    'Pogo'
];

export const lastName = [
    'Snickerdoodle',
    'Wigglesworth',
    'Fizzletop',
    'Noodleman',
    'Biscuitbottom',
    'Flapjackington',
    'Quackenbush',
    'Puddlesworth',
    'Jibberjaws',
    'Gigglesworth',
    'Tootsieroll',
    'Scoobydoo',
    'Tinkerbell',
    'Bumpkinpatch',
    'Chuckleberry',
    'Ziggyzag',
    'Doodlebugger',
    'Pogostick',
    'Wallyworld',
    'Snookumsnoodle'
];

  export const smileys = ["😀", "😁", "😂", "🤣", "😃", "😄", "😅", 
  "😆", "😉", "😊", "😋", "😎", "😍", "😘", "😜", "😝", "🥰", "🤩", 
  "🥳", "😇", "🤪", "🤑", "🤗", "😏", "😌", "🤓", "🧐", "😈", "👿", 
  "💀", "👻", "👽", "🤖", "😺", "😸", "😹", "😻", "😼", "😽", "🙀", 
  "🤡", "🤠", "🥰", "🥺", "🤤", "🤢", "🤮", "🥵", "🥶", "🥴", "😵", 
  "🤯", "🤬", "😷", "🥸", "👹", "👺", "💩", "👶", "🧒", "👦", "👧", 
  "🧑", "👩", "👨", "👩‍🦱", "👨‍🦱", "👩‍🦰", "👨‍🦰", "👱‍♀️", "👱‍♂️", "👩‍🦳", "👨‍🦳", 
  "👩‍🦲", "👨‍🦲", "👵", "👴", "🐶", "🐱", "🐭", "🐹", "🐰", "🦊", "🦝", 
  "🐻", "🐼", "🦁", "🐯", "🐴", "🦄", "🐮", "🐷", "🦓", "🦌", "🐿️", 
  "⚽", "🏀", "🏈", "⚾️", "🎾", "🏐", "🏉", "🎱", "🏓", "🏸", "🥊", 
  "🥋", "🎽", "⛳️", "🏹", "🎣", "🥇", "🥈", "🥉", "🏆",];